---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: client-bc
  creationTimestamp: 
parameters:
- name: NAME
  displayName:
  description: the module name entered when run yo bcdk:pipeline, which is tfrs
  required: true  
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: VERSION
  displayName:
  description:  image tag name for output
  required: true
- name: GIT_URL
  displayName:
  description: tfrs repo
  value: https://github.com/bcgov/tfrs.git
  required: true
- name: GIT_REF
  displayName:
  description: tfrs branch name of the pr
  required: true   
objects:
- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    name: ${NAME}-client${SUFFIX}
    creationTimestamp: 
    annotations:
      description: Defines how to build the client / front end image
  spec:
    triggers:
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
    runPolicy: Serial
    source:
      type: Dockerfile
      dockerfile: |-
        FROM tfrs-client-angular-app:build-1.0.0-1696
        COPY * /tmp/app/dist/
        CMD  /usr/libexec/s2i/run
      images:
      - from:
          kind: ImageStreamTag
          name: ${NAME}-client-angular-app${SUFFIX}:${VERSION}
        as: 
        paths:
        - sourcePath: "/opt/app-root/src/public/."
          destinationDir: tmp
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: nginx-runtime:latest
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}-client${SUFFIX}:${VERSION}
    resources:
      limits:
        cpu: '2'
        memory: 4Gi
    postCommit: {}
    nodeSelector: 
  status:
    lastVersion: 0
