---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: client-dc
  creationTimestamp: 
parameters:
- name: NAME
  displayName:
  description: the module name entered when run yo bcdk:pipeline, which is zeva
  required: true
- name: SUFFIX
  displayName:
  description: sample is -pr-0
  required: true
- name: KEYCLOAK_AUTHORITY
  displayName: keycloak.authority
  description: Values https://dev.oidc.gov.bc.ca/auth/realms/tfrs-dev https://test.oidc.gov.bc.ca/auth/realms/tfrs
    https://oidc.gov.bc.ca/auth/realms/tfrs
  required: true
- name: KEYCLOAK_CLIENT_ID
  displayName: keycloak.client_id
  description: Values tfrs-dev tfrs tfrs
  required: true
- name: KEYCLOAK_CALLBACK_URL
  displayName: keycloak.callback_url
  description: Values https://dev-lowcarbonfuels.pathfinder.gov.bc.ca/authCallback
    https://test-lowcarbonfuels.pathfinder.gov.bc.ca/authCallback https://lowcarbonfuels.gov.bc.ca/authCallback
  required: true
- name: KEYCLOAK_LOGOUT_URL
  displayName: keycloak.post_logout_url
  description: Values https://logontest.gov.bc.ca/clp-cgi/logoff.cgi?returl=https%3A%2F%2Fdev-lowcarbonfuels.pathfinder.gov.bc.ca%2F
    https://logontest.gov.bc.ca/clp-cgi/logoff.cgi?returl=https%3A%2F%2Ftest-lowcarbonfuels.pathfinder.gov.bc.ca%2F
    https://logon.gov.bc.ca/clp-cgi/logoff.cgi?returl=https%3A%2F%2Flowcarbonfuels.gov.bc.ca%2F
  required: true
- name: FRONTEND_HOST_NAME
  displayName: Route host name
  description: Route host name
  required: true
objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${NAME}-client${SUFFIX}
  spec:
    ports:
    - name: web
      protocol: TCP
      port: 8080
      targetPort: 8080
    selector:
      name: ${NAME}-client${SUFFIX}
    type: ClusterIP
    sessionAffinity: None
  status:
    loadBalancer: {}
- kind: Route
  apiVersion: v1
  metadata:
    name: ${NAME}-client${SUFFIX}
    creationTimestamp: 
    labels:
      frontend: 'true'
    annotations: {}
  spec:
    host: ${FRONTEND_HOST_NAME}
    to:
      kind: Service
      name: ${NAME}-client${SUFFIX}
      weight: 100
    port:
      targetPort: web
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    wildcardPolicy: None
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${NAME}-keycloak-config${SUFFIX}
    creationTimestamp: 
  data:
    ssss: ${KEYCLOAK_CLIENT_ID}
    features.js: |
      window.tfrs_config = {
        "keycloak.enabled": true,
        "keycloak.authority": "${KEYCLOAK_AUTHORITY}" ,
        "keycloak.client_id": "${KEYCLOAK_CLIENT_ID}",
        "keycloak.callback_url": "${KEYCLOAK_CALLBACK_URL}",
        "keycloak.post_logout_url": "${KEYCLOAK_LOGOUT_URL}",
        "debug.enabled": false,
        "secure_document_upload.enabled": true,
        "secure_document_upload.max_file_size": 50000000,
        "fuel_codes.enabled": true,
        "keycloak.custom_login": true,
        "credit_transfer.enabled": true,
        "compliance_reporting.enabled": true,
        "credit_calculation_api.enabled": true,
        "compliance_reporting.starting_year": 2017,
        "compliance_reporting.create_effective_date": "2019-01-01",
        "exclusion_reports.create_effective_date": "2019-01-01",
        "exclusion_reports.enabled": true
      };
