apiVersion: template.openshift.io/v1
kind: Template
parameters:
- name: KEYCLOAK_SA_CLIENT_SECRET
  description: teh keycloak sa client secret
  required: true
- name: DJANGO_SECRET_KEY
  description: "secret used by Django"
  from: "[a-zA-Z0-9]{50}"
  generate: expression
  required: true
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: keycloak-sa-client-secret
  stringData:
    KEYCLOAK_SA_CLIENT_SECRET: ${KEYCLOAK_SA_CLIENT_SECRET}
- apiVersion: v1
  kind: Secret
  metadata:
    annotations: null
    name: django-secret-key
  stringData:
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}

    